### ISSUE TITLE
Cannot use nuxtSocket in asyncdata, fetch ('state' undefined)

### ISSUE THREAD

**Issue by sungle3737** [richardeschloss/nuxt-socket-io#117]
![image](https://user-images.githubusercontent.com/27716524/86554235-fdeed780-bf87-11ea-81d5-4798e9f38051.png)

```
async fetch({ app }) {
  app.$nuxtSocket({ name: 'blabla' })
}
```
or 
```
async asyncData({ store }) {
  store.$nuxtSocket({ name: 'blabla' })
}
```

These two examples result in the issue shown above. Can't I call socket before render?

**Comment by richardeschloss** [comment]
Hi friend,

You should be able to, but it appears as though there are minor, but important details to be aware of. First, $nuxtSocket requires vuex store to be defined "the Nuxt way" as addressed in #103 :

```js
export const state = () => ({}) // defined state (empty, but defined)
```

If the above code doesn't exist, then the vuex store is undefined, and that will cause the error you see. 

Second, the $nuxtSocket function gets injected into the context, so your first snippet should work. But in order to do the emit, you need the socket instance that is returned by the $nuxtSocket function:

```js
async fetch({ app }) {
  var socket = app.$nuxtSocket({ name: 'blabla' }) // Get socket instance
  socket.emit( /* Emit event */ )
  socket.on( /* Listen event */ )
}
```

Please let me know how far this gets you. It's my sunday evening here, so I apologize I may not be able to investigate this further until tomorrow. I hope this helps though.

**Comment by sungle3737** [comment]
First, Thanks for reply on Sunday

- I had nuxt way store,$nuxtSocket function injected to app in fetch scope, but above error still on
- Even I  set nuxt as spa, this problem still happen

I think they can't find store in fetch, asyncData scope not like this.$store

**Comment by richardeschloss** [comment]
Hmm. Ok, I think in that mode you'd actually use `this` not `context`:

```js
fetch() {
  var socket = this.$nuxtSocket({...}). 
} 
```

I just created a simple component, and it seems $nuxtSocket is on `this` and it seems that `this.$store` is indeed there. Can you please let me know if that helps?

**Comment by sungle3737** [comment]
No My app is `universal` mode, I just test same code once in spa mode

### in fetch, asyncData
- I can access $nuxtSocket 
- there is nuxt store ~/store/index.js
```
export const state = () => ({
  ...
})

export const mutations = {
  ...
}
```

but while $nuxtSocket function error happens!

**Comment by richardeschloss** [comment]
This works in universal mode. I just tested it:
```js
fetch() {
  var socket = this.$nuxtSocket({
    name: 'stories'
  })
  console.log(socket) // Works. I see the socket instance in console log. 
},
```

**Comment by sungle3737** [comment]
Wow. argument.. Solved Thanks
```
fetch() {
    console.log(this.$nuxtSocket)
  },
```
- `Function`
```
  fetch({ store, app }) {
    console.log(this.$nuxtSocket)
  },
```
- `undefined`
`this` is difficult i can't understand why this is overwrited

**Comment by sungle3737** [comment]
```javascript
fetch() {
  const socket = this.$nuxtSocket({
    name: 'stories'
  }),
},
fetchOnServer: false
```

My best solution was this, when i fetch on server(without `fetchonserver` option), socket couldn't find host like this image

![image](https://user-images.githubusercontent.com/27716524/86730145-2f8b9f80-c069-11ea-923d-08a4eb6ed5a8.png)

**Comment by richardeschloss** [comment]
Hi fetch on server will work on the server if you specify the URL of the
Socketio server in nuxt config. Most likely , the URL isn't specified and
as a result, the plugin tries to connect to `window.location`. the window
only exists on the client, which is why your logs show undefined in the
connection string. I.e., there is no browser server-side

**Comment by sungle3737** [comment]
I got it Thanks!
