### ISSUE TITLE
Help wanted GET http://127.0.0.1:3000/socket.io/?EIO=3&transport=polling&t=NDdzArE 404 (OK)

### ISSUE THREAD

**Issue by guoxiangke** [richardeschloss/nuxt-socket-io#124]
Hi, can u help on this issue? (Error: " GET http://127.0.0.1:3000/socket.io/?EIO=3&transport=polling&t=NDdzArE 404 (OK)")
I exactly follow the document and the articles from medium.
my nuxt.config.js like this
![image](https://user-images.githubusercontent.com/1160703/87880193-42678200-ca22-11ea-8944-3f84e27f768b.png)

while when I use 
> url: 'https://nuxt-socket-io.herokuapp.com', 

the example works.

no need to change the server/index.ts like this, right?

```js
// eslint-disable-next-line import/order
const server = require('http').createServer(app.callback())
const io = require('socket.io')(server)
io.on('connection', function(socket: any) {
  console.log('a user connected', socket)
})
```

**Comment by richardeschloss** [comment]
Hi friend, you're really close, I feel bad for telling you the answer, because you're centimeters away from having figured it out yourself. However, if you are pressed for time and require the solution quickly, please, read below:

The docs for what you want are described in [Automatic IO Server Registration](https://nuxt-socket-io.netlify.app/configuration#automatic-io-server-registration)

So, you need to have an IO server running and listening at the correct port in order for the IO client to connect to it, otherwise you'll encounter the 404 errors:

At a minimum, you need:
`server/io.js`:
```js
export default function(socket, io) {
  /* You can work with socket here if you like */
  return Object.freeze({
    /* api here */
    method1(msg) { // if client emits "method1" with msg, this method will be called
    }
  })
}
``` 

Then on your client (in any vue page):
```
mounted() {
  this.socket = this.$nuxtSocket({ }) // will connect to your default "main" socket
}
```

The console logs should say when client is connected.

**Comment by guoxiangke** [comment]
Does the server/io.js support typescript?
before I use TS for this file and server/io/index.ts server/io/example.ts
but now I changed back to js of those 3 files, still 404, thanks in advance.
![image](https://user-images.githubusercontent.com/1160703/87897052-bc2c5980-ca7c-11ea-96bc-e7d65b43b9c3.png)

**Comment by richardeschloss** [comment]
Currently, typescript for the IO server isn't supported. The module only looks for the ".js" extension when searcing for IO services. I may consider support in the future.

**Comment by guoxiangke** [comment]
> Currently, typescript for the IO server isn't supported. The module only looks for the ".js" extension when searcing for IO services. I may consider support in the future.

Thanks, now I changed to .js , still not work, does it need my server.ts => server.js? or need All my nuxt to js?

**Comment by richardeschloss** [comment]
I haven't tried with typescript, but I think it may work actually. The module only looks for the ".js" extension when searcing for IO services. The root of your issue has to do with spelling: the file "server/index.js" should be renamed to "server/**io.js**". 

If you need to specify a different filename, you can do so by specifying the `ioSvc` option in `nuxt.config`:

```js
io: {
  server: {
    ioSvc: /path/to/your/io // so I think if you specified with the ".ts" extension, it would work
  }
}
```

See also: [IO Server overrides](https://nuxt-socket-io.netlify.app/configuration#io-server-overrides)

If your .ts files can be require'd, it should still work

**Comment by richardeschloss** [comment]
Also, if you do have this code already in server/index:

```
const server = require('http').createServer(app.callback())
const io = require('socket.io')(server)
io.on('connection', function(socket: any) {
  console.log('a user connected', socket)
})
```

then this will compete / conflict with what the IO module is trying to do and should be removed if planning on using the same host/port as the Nuxt app becuse the IO module is trying to start the server automatically on that port when you have IO folders and files.

**Comment by guoxiangke** [comment]
> I haven't tried with typescript, but, upon reconsidering, I think it may work actually. The module only looks for the ".js" extension when searcing for IO services. By default, it searches for server/io.js to be the root of the IO server services.
> 
> If you need to specify a different filename, such as that with a "ts" extension, you can do so by specifying the `ioSvc` option in `nuxt.config`:
> 
> ```js
> io: {
>   server: {
>     ioSvc: /path/to/your/io // so I think if you specified with the ".ts" extension, it would work
>   }
> }
> ```
> 
> See also: [IO Server overrides](https://nuxt-socket-io.netlify.app/configuration#io-server-overrides)
> 
> If your .ts files can be require'd, it should still work:
> 
> ```js
> io: {
>   server: {
>     ioSvc: './server/io.js' // .js extension works. the demo app on heroku works because it's based off this git repo exactly
>     // ioSvc: './server/io.ts' // so I think if you specified with the ".ts" extension, it would also work
>   }
> }
> ```
> 
> I don't think the rest of your app needs to be changed. It should be fine as is, since typescript compiles to javascript.

not work, hope can support TS. thanks.

**Comment by richardeschloss** [comment]
Hi, 

Ok, I pushed a working example to branch [issue/124](https://github.com/richardeschloss/nuxt-socket-io/tree/issue/124) that should address your concerns. Your issue can be broken into smaller, manageable issues:

1) First, making sure the IO server gets registered correctly.  
1a) if you run just *nuxt*, no further action is needed, because Nuxt starts up with its own server that nuxt-socket-io simply uses.
1b) if you are running your *own* server/index.js that will start up Nuxt, then you'll want to do what my [server/index.js](https://github.com/richardeschloss/nuxt-socket-io/blob/issue/124/server/index.js) is doing. The nuxt-socket-io module waits to receive the Nuxt hook "listen" before registering the IO services. 

In that branch, I added "// RES" (my initials) where I added / changed code and console statements.

If the nuxt hook gets called correctly, you'll see it in the console "NUXT HOOK: LISTENING". I suggest trying both "nuxt" and your "node server/index.js" to help troubleshoot. I did and saw success with both ways.

2) Support for typescript files (this is a separate issue, probably feature request)

I added ".ts" to the supported extensions in [io/module.js](https://github.com/richardeschloss/nuxt-socket-io/blob/issue/124/io/module.js). I also added console log statements to print out the found io service files. This should aid in troubleshooting. You'll want to copy this module.js file over to your node_modules/nuxt-socket-io/module.js (suggest backing up existing module.js file before copying)

In that branch, I have a working *typescript* file "server/io/newfile.ts" which will receive an event "hi" and respond with "world". The [pages/index.vue](https://github.com/richardeschloss/nuxt-socket-io/blob/issue/124/pages/index.vue) is able to successfully receive the "world" response in the mounted hook.

Please let me know how far you get. Thanks.

**Comment by guoxiangke** [comment]
Thanks for your response, I test the issues/124 branch, it works.
but still not work on my project.
I replaced the [io/module.js](https://raw.githubusercontent.com/richardeschloss/nuxt-socket-io/issue/124/io/module.js) from this branch.
and here is my [server/index.ts](https://github.com/guoxiangke/nuxtChat/blob/master/server/index.ts) which I try my best as yours.
here are my [server/io.js|ts](https://github.com/guoxiangke/nuxtChat/tree/master/server) and [server/io/xxxx.ts|ts](https://github.com/guoxiangke/nuxtChat/tree/master/server/io)
here is my [nuxt.config.js](https://github.com/guoxiangke/nuxtChat/blob/master/nuxt.config.js)
and here is my [vue components](https://github.com/guoxiangke/nuxtChat/blob/master/pages/conversation/index.vue)

Many thanks in advance.

**Comment by richardeschloss** [comment]
Ok, your server isn't doing what my server is doing, and the small difference is important.

You're doing:
```
await app.listen()
```

I'm doing:
```
await nuxt.listen()  // calls "listen" hook
```

The key difference is that `nuxt.listen` will call the ["listen" hook](https://github.com/nuxt/nuxt.js/blob/9b29124d319fb0fd668a5c7129315325d445c566/packages/server/src/server.js#L362) used by the module. 

So the easy solution would be to better match my server.js file if you can. Otherwise you'd have to call the Nuxt hook yourself:

```
const server = http.createServer(app.callback())
await server.listen(port, host)
nuxt.callHook('listen', server) // where server would be your koa's server instance. This would call the "listen" hook used by nuxt
```

I personally think "callHook" will be more difficult than the first way shown.

Anyway, this is starting to turn into consulting for your specific needs. If you require further consulting, my rate is $250 / hr. Thanks.

**Comment by flychat** [comment]
Thank you very much, it works with 
```
  await app.listen(port, host)
  await nuxt.listen('3001')
```
I use another port for socket.io

**Comment by guoxiangke** [comment]
Thank you very much, it works with
```
  await app.listen(port, host)
  await nuxt.listen('3001')
```
I use another port for socket.io
